import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import { MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';
import { DoubleNavbar } from '@/components/DoubleNavbar';
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider defaultColorScheme="light">
          <DoubleNavbar />
          <main style={{ marginLeft: '300px', minHeight: '100vh' }}>
            {children}
          </main>
        </MantineProvider>
      </body>
    </html>
  );
}
